name: Integration Tests

on: push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Cypress Run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          working-directory: client
